---
# tasks file for mediawiki
- name: include assert.yml
  include_tasks: assert.yml

- name: create directory
  file:
    path: "{{ mediawiki_destination }}"
    state: directory

- name: install requirements
  package:
    name: "{{ mediawiki_requirements }}"
    state: present
  notify:
    - restart httpd

- name: install mediawiki
  unarchive:
    src: "{{ mediawiki_source }}"
    dest: "{{ mediawiki_destination }}"
    remote_src: yes
    creates: "{{ mediawiki_destination }}/mediawiki-{{ mediawiki_version }}"
    setype: httpd_sys_script_rw_t

- name: link mediawiki to versioned directory
  file:
    src: "{{ mediawiki_destination }}/mediawiki-{{ mediawiki_version }}"
    dest: "{{ mediawiki_destination }}/mediawiki"
    state: link

- name: link mediawiki to docroot
  file:
    src: "{{ mediawiki_destination }}/mediawiki"
    dest: "{{ mediawiki_docroot }}/mediawiki"
    state: link
